import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BobaShopCard from '../components/BobaShopCard'
import bobaTea from '../public/bubble-tea.jpg'

export default function Home() {
  const JSON_DATA = [
    {
      id: 0,
      name: 'Tan Cha',
      yelp_rating: 4,
      shop_restaurant_mc_score: 2.5,
      yelp_url: 'https://www.yelp.com/',
      reviews: [
        {
          text: 'great place',
          yelp_review: 4,
          mycase_review: 4,
        }
      ],
    },
    {
      id: 1,
      name: 'Boba Shop',
      yelp_rating: 3.4,
      shop_restaurant_mc_score: 3.8,
      yelp_url: 'https://www.yelp.com/',
      reviews: [
        {
          text: 'great place',
          yelp_review: 4,
          mycase_review: 4,
        }
      ],
    },
    {
      id: 2,
      name: 'Tapioca Express',
      yelp_rating: 3.3,
      shop_restaurant_mc_score: 2.7,
      yelp_url: 'https://www.yelp.com/',
      reviews: [
        {
          text: 'great place',
          yelp_review: 4,
          mycase_review: 4,
        }
      ],
    },
    {
      id: 3,
      name: 'Ocha Tea Cafe',
      yelp_rating: 3.4,
      shop_restaurant_mc_score: 3,
      yelp_url: 'https://www.yelp.com/',
      reviews: [
        {
          text: 'great place',
          yelp_review: 4,
          mycase_review: 4,
        }
      ],
    }
  ]

  const sort_by_key = (data, key) => {
    return data.sort((a, b) =>
    {
      var x = a[key]; 
      var y = b[key];
      return ((x > y) ? -1 : ((x < y) ? 1 : 0));
    });
  }

  const sortedData = sort_by_key(JSON_DATA, 'shop_restaurant_mc_score');

  return (
    <div className={styles.container}>
      <Head>
        <title>Boba Hack Day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image 
          src={bobaTea} 
          alt="boba tea" 
          width={300}
          height={300}
        />
        <h1 className={styles.title}>
          Boba Hack Day
        </h1>

        <p className={styles.description}>
          Using natural language processing to give boba shops a more accurate rating based on customer reviews.
        </p>

        <div className={styles.grid}>
          {sortedData && sortedData.map((shopData, index) => 
            <BobaShopCard
              key={`boba-shop-${index}`} 
              bobaShop={shopData}
            />)
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
