import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BobaShopCard from '../components/BobaShopCard'

export default function Home() {
  const JSON_DATA = [
    {
      name: 'tan cha',
      yelp_rating: 4,
      shop_restaurant_mc_score: 2.5,
      yelp_url: 'www.yelp.com',
      reviews: [
        {
          text: 'great place',
          yelp_review: 4,
          mycase_review: 4,
        }
      ],
    }
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Boba Hack Day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Boba Hack Day
        </h1>

        <p className={styles.description}>
          Using natural language processing to give boba shops a more accurate rating based on customer reviews.
        </p>

        <div className={styles.grid}>
          {JSON_DATA && JSON_DATA.map((shopData, index) => 
            <BobaShopCard 
              key={`boba-shop-${index}`} 
              bobaShop={shopData}
            />)
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
